Resources:
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
        - fourmeal-api-application-user-role
  Ec2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      KeyName: fourmeal-application-keys
      ImageId: ami-0e01ce4ee18447327
      InstanceType: t2.micro
      IamInstanceProfile:
        Ref: InstanceProfile
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            aws s3 sync s3://fourmeal-colbywar /home/ec2-user
            tar -xzf /home/ec2-user/amazon-corretto-11-x64-linux-jdk.tar.gz -C /opt
            export PATH=/opt/amazon-corretto-11.0.6.10.1-linux-x64/bin:$PATH
            nohup java -jar /home/ec2-user/fourmeal-1.1.0.jar &
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
